Subject: Add a missing include at v4l2_driver.h From: Carl Karsten <carl@personnelware.com> Date: Thu, 28 Feb 2008 15:21:51 -0600
Adding #include <stddef.h> solves a build problem I had on Ubnutu.

v4l-dvb/v4l2-apps/test$ make
CC driver-test.o
In file included from driver-test.c:17:
../lib/v4l2_driver.h:26: error: expected specifier-qualifier-list before 'size_t'
make: *** [driver-test.o] Error 1

Thanks to Carl Karsten <carl@personnelware.com> for pointing this issue.

CC: Carl Karsten <carl@personnelware.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@infradead.org>