v4l2-compliance: add missing 'class' keyword after 'friend'
This led to this compile error for some compilers:

In file included from v4l2-compliance.h:31,
                 from v4l2-compliance.cpp:37:
./cv4l-helpers.h:9: error: a class-key must be used when declaring a friend
./cv4l-helpers.h:9: error: friend declaration does not name a class or function

I'm not sure why this doesn't fail for all compilers, weird.

Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
Reported-by: Prabhakar Lad <prabhakar.csengg@gmail.com>