qv4l2: fix Qt6 compile (missing QActionGroup header)
Fixes:

  ../qv4l2/qv4l2.cpp:246:36: error: invalid use of incomplete type ‘class QActionGroup’
    246 |         grp = new QActionGroup(menu);
        |                                    ^

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>