configure.ac: don't enable pthread with static libraries
At least on Fedora, static libraries using pthread fail with:

	/usr/bin/ld: ../../lib/libdvbv5/.libs/libdvbv5.a(libdvbv5_la-dvb-dev-local.o): undefined reference to symbol 'pthread_cancel@@GLIBC_2.2.5'
	/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
	collect2: error: ld returned 1 exit status

Maybe this could be fixed somehow, but, as this is not an
usual scenario, just disable it if configure is called
with:
	./configure --disable-shared

Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>