meson: libv4lconvert helpers need fork support
- libv4lconvert helpers (v4lconvert_helper_decompress,
  v4lconvert_helper_cleanup, ...) need fork() support, so add additional
  dependency for HAVE_LIBV4LCONVERT_HELPERS

Fixes:

  FAILED: contrib/test/v4l2grab
  .../bootlin-armv7m-uclibc/host/bin/arm-linux-gcc  -o contrib/test/v4l2grab contrib/test/v4l2grab.p/v4l2grab.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-elf2flt=-r -static -Wl,--start-group lib/libv4l2/libv4l2.a lib/libv4lconvert/libv4lconvert.a -largp -pthread -ldl -lm -lrt -Wl,--end-group
  .../bootlin-armv7m-uclibc/host/opt/ext-toolchain/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: lib/libv4lconvert/libv4lconvert.a(libv4lconvert.c.o): in function `v4lconvert_destroy':
  libv4lconvert.c:(.text+0x5c0): undefined reference to `v4lconvert_helper_cleanup'
  .../bootlin-armv7m-uclibc/host/opt/ext-toolchain/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: lib/libv4lconvert/libv4lconvert.a(libv4lconvert.c.o): in function `v4lconvert_convert_pixfmt':
  libv4lconvert.c:(.text+0x1450): undefined reference to `v4lconvert_helper_decompress'
  collect2: error: ld returned 1 exit status

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
(cherry picked from commit b22a2838ca31ea066f8bbc4561c3a602bd274441)
Signed-off-by: Gregor Jasny <gjasny@googlemail.com>