v4l2-tracer: use __s64 instead of long
This fixes compiler errors when building on the 32 bit architecture.

They are all of this type:

../../include/linux/videodev2.h:2583:33: error: narrowing conversion of 3222820424 from unsigned int to long int [-Wnarrowing]
 2583 | #define VIDIOC_S_EXT_CTRLS      _IOWR('V', 72, struct v4l2_ext_controls)
      |                                 ^~~~~
v4l2-tracer-info-gen.h:2069:11: note: in expansion of macro VIDIOC_S_EXT_CTRLS
 2069 |         { VIDIOC_S_EXT_CTRLS,   "VIDIOC_S_EXT_CTRLS" },
      |           ^~~~~~~~~~~~~~~~~~

and:

../../include/linux/videodev2.h:2583:33: error: narrowing conversion of 3222820424 from unsigned int to long int [-Wnarrowing]
 2583 | #define VIDIOC_S_EXT_CTRLS      _IOWR('V', 72, struct v4l2_ext_controls)
      |                                 ^~~~~
retrace.cpp:1273:14: note: in expansion of macro VIDIOC_S_EXT_CTRLS
 1273 |         case VIDIOC_S_EXT_CTRLS:
      |              ^~~~~~~~~~~~~~~~~~

Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>