v4l2-compliance: Fix build error clang TOT
We define the fallthrough keyword in compiler.h. but he c++ header files
uses as well that keyword and it get confused.

We could swap the order of the defines (like the other files in this
directory do). But this file does not use fallthrough, so we can remove
this define completely.

In file included from utils/v4l2-compliance/v4l2-test-time32-64.cpp:20:
In file included from v4l-utils/utils/v4l2-compliance/v4l2-compliance.h:24:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/map:2193:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/functional:540:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/__functional/boyer_moore_searcher.h:27:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/vector:326:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/__format/formatter_bool.h:19:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/__format/formatter_integral.h:21:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/__format/formatter_output.h:22:
In file included from prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/__format/parser_std_format_spec.h:29:
prebuilts/clang/host/linux-x86/clang-r536225/include/c++/v1/__format/unicode.h:465:9: error: expected ']'
  465 |       [[fallthrough]];
      |         ^
https://github.com/llvm/llvm-project/blob/ccfcc9117b70828390019979219fa26ce77c3900/libcxx/include/__format/unicode.h#L465

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Signed-off-by: Hans Verkuil <hverkuil@xs4all.nl>