media-info: add missing sys/stat.h include (for dev_t)
Fixes musl libc compile failure:

  In file included from ../utils/v4l2-tracer/v4l2-tracer-common.h:11,
                   from ../utils/v4l2-tracer/trace.h:9,
                   from ../utils/v4l2-tracer/trace-helper.cpp:6:
  ../utils/common/media-info.h:40:34: error: ‘dev_t’ has not been declared
     40 | int mi_get_dev_t_from_fd(int fd, dev_t *dev);
        |                                  ^~~~~
  ../utils/common/media-info.h:48:39: error: ‘dev_t’ was not declared in this scope; did you mean ‘div_t’?
     48 | std::string mi_get_devpath_from_dev_t(dev_t dev);
        |                                       ^~~~~
        |                                       div_t

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
(cherry picked from commit b66b50001d299222d089820ec4c48a0577a482c1)
Signed-off-by: Gregor Jasny <gjasny@googlemail.com>