keytable: fix BPF protocol compilation on mips
clang -idirafter /usr/local/include -idirafter
+/usr/lib/llvm-6.0/lib/clang/6.0.1/include -idirafter
+/usr/include/mips64el-linux-gnuabi64 -idirafter /usr/include
+-I../../../include -target bpf -O2 -c grundig.c
> In file included from grundig.c:5:
> In file included from ../../../include/linux/lirc.h:10:
> In file included from /usr/include/linux/types.h:9:
> In file included from /usr/include/linux/posix_types.h:36:
> In file included from
+/usr/include/mips64el-linux-gnuabi64/asm/posix_types.h:13:
> /usr/include/mips64el-linux-gnuabi64/asm/sgidefs.h:19:2: error: Use a Linux
+compiler or give up.
> #error Use a Linux compiler or give up.

This requires __linux__ to be defined.

Signed-off-by: Sean Young <sean@mess.org>