media-ctl: Fix a compilation bug introduced by changeset 7a21d66983f7
options.c:56:9: warning: missing terminating " character
options.c:56:9: error: missing terminating " character
options.c:57:71: error: expected ')' before ';' token
options.c:57:2: warning: passing argument 1 of 'printf' makes pointer from integer without a cast [-Wint-conversion]
options.c:94:1: error: expected ';' before '}' token
options.c:42:15: warning: unused variable 'i' [-Wunused-variable]

Clearly, nobody tested this patch before merging it.

Fixes: 7a21d66983f7 ("media-ctl: Print information related to a single entity")

Cc: Sakari Ailus <sakari.ailus@linux.intel.com>
Cc: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>